const reports = [
  {
    name: "John Doe",
    reason: "Unauthorized access",
    reportDate: "2023-10-08",
    processingStatus: "pending",
  },
  {
    name: "Jane Smith",
    reason: "Harassment",
    reportDate: "2023-09-25",
    processingStatus: "accepted",
  },
  {
    name: "Mike Johnson",
    reason: "Theft",
    reportDate: "2023-09-15",
    processingStatus: "cancelled",
  },
  {
    name: "Sarah Wilson",
    reason: "Vandalism",
    reportDate: "2023-10-02",
    processingStatus: "pending",
  },
  {
    name: "Emily Brown",
    reason: "Fraud",
    reportDate: "2023-09-30",
    processingStatus: "pending",
  },
  {
    name: "David Thomas",
    reason: "Assault",
    reportDate: "2023-09-18",
    processingStatus: "accepted",
  },
  {
    name: "Olivia Davis",
    reason: "Bullying",
    reportDate: "2023-09-22",
    processingStatus: "cancelled",
  },
  {
    name: "Daniel Wilson",
    reason: "Forgery",
    reportDate: "2023-09-28",
    processingStatus: "pending",
  },
  {
    name: "Sophia Martin",
    reason: "Harassment",
    reportDate: "2023-09-12",
    processingStatus: "accepted",
  },
  {
    name: "Liam Anderson",
    reason: "Theft",
    reportDate: "2023-10-05",
    processingStatus: "pending",
  },
  {
    name: "John Doe",
    reason: "Unauthorized access",
    reportDate: "2023-10-08",
    processingStatus: "pending",
  },
  {
    name: "Jane Smith",
    reason: "Harassment",
    reportDate: "2023-09-25",
    processingStatus: "accepted",
  },
  {
    name: "Mike Johnson",
    reason: "Theft",
    reportDate: "2023-09-15",
    processingStatus: "cancelled",
  },
  {
    name: "Sarah Wilson",
    reason: "Vandalism",
    reportDate: "2023-10-02",
    processingStatus: "pending",
  },
  {
    name: "Emily Brown",
    reason: "Fraud",
    reportDate: "2023-09-30",
    processingStatus: "pending",
  },
  {
    name: "David Thomas",
    reason: "Assault",
    reportDate: "2023-09-18",
    processingStatus: "accepted",
  },
  {
    name: "Olivia Davis",
    reason: "Bullying",
    reportDate: "2023-09-22",
    processingStatus: "cancelled",
  },
  {
    name: "Daniel Wilson",
    reason: "Forgery",
    reportDate: "2023-09-28",
    processingStatus: "pending",
  },
  {
    name: "Sophia Martin",
    reason: "Harassment",
    reportDate: "2023-09-12",
    processingStatus: "accepted",
  },
  {
    name: "Liam Anderson",
    reason: "Theft",
    reportDate: "2023-10-05",
    processingStatus: "pending",
  },
  // Additional report objects
  {
    name: "Emma Johnson",
    reason: "Fraud",
    reportDate: "2023-09-27",
    processingStatus: "accepted",
  },
  {
    name: "Benjamin Wilson",
    reason: "Vandalism",
    reportDate: "2023-10-01",
    processingStatus: "pending",
  },
  {
    name: "Ava Thompson",
    reason: "Harassment",
    reportDate: "2023-09-20",
    processingStatus: "cancelled",
  },
  {
    name: "James Davis",
    reason: "Unauthorized access",
    reportDate: "2023-09-17",
    processingStatus: "pending",
  },
  {
    name: "Mia Anderson",
    reason: "Assault",
    reportDate: "2023-09-29",
    processingStatus: "accepted",
  },
  {
    name: "William Johnson",
    reason: "Theft",
    reportDate: "2023-09-26",
    processingStatus: "cancelled",
  },
  {
    name: "Sophie Wilson",
    reason: "Bullying",
    reportDate: "2023-09-24",
    processingStatus: "pending",
  },
  {
    name: "Alexander Smith",
    reason: "Forgery",
    reportDate: "2023-09-16",
    processingStatus: "accepted",
  },
  {
    name: "Charlotte Brown",
    reason: "Harassment",
    reportDate: "2023-09-23",
    processingStatus: "cancelled",
  },
  {
    name: "Henry Thompson",
    reason: "Unauthorized access",
    reportDate: "2023-10-03",
    processingStatus: "pending",
  },
  {
    name: "Amelia Davis",
    reason: "Theft",
    reportDate: "2023-09-19",
    processingStatus: "pending",
  },
];

export default reports;
